#setup consul_server
- hosts: consul_server
  become: yes
  become_user: root
  roles:
    - consul


#setup console client
- hosts: all:!consul_server
  become: yes
  become_user: root
  roles:
    - consul