- name: Install php7
  become: yes
  apt:
    name : [ php7.4, php7.4-mysql, php7.4-gd, php-ssh2, php7.4-fpm, php-fpm, php-common, php-mbstring, php-xmlrpc, php-soap, php-gd, php-xml, php-intl, php-mysql, php-cli, php-ldap, php-zip, php-curl]
    state : present

- name: Setup php-fpm
  replace: dest=/etc/php/7.4/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx
  become: yes

# - name: Add php settings
#   template: src=../../nginx/templates/sites-available/nginx-wp-common.conf dest=/etc/nginx/conf.d/nginx-wp-common.conf owner=www-data group=www-data mode=0644
#   become: yes