all:
    vars:
        ansible_user: d
    hosts:
        node1:
            ansible_host : 10.55.254.133
            package:
                name: ntpdate
                state: present
            consul_server : yes
        node2:
            ansible_host : 10.55.254.134
            webservers : yes
        node3:
            ansible_host : 10.55.254.132
    children:
        consul_server:
            hosts:
                node1:
        webservers:
            hosts:
                node3: